### ISSUE TITLE
Critical error for Php 8

### ISSUE THREAD

**Issue by SudiptaJana-Codeclouds** [thingsym/multi-device-switcher#12]
I am getting a critical error for PHP 8 on my WordPress site. "create_function" this function is deprecated in PHP 8. Attached a screenshot for reference.
![image](https://user-images.githubusercontent.com/75357176/185846684-d698317c-0fc0-46f2-af07-a85e410957cb.png)

**Comment by thingsym** [comment]
This issue is not about the Multi Device Switcher plugin.
The plugin that corresponds to the issue is Mobile Smart.
https://wordpress.org/plugins/mobile-smart/
